Restore original handling for missing themes in Makefile

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -6,9 +6,14 @@ help:
 
 themes/scientific-python-hugo-theme:
 	@if [ ! -d "$<" ]; then \
-	  mkdir -p themes; \
-	  cd themes; \
-	  ln -s ../.. scientific-python-hugo-theme; \
+      echo "*** ERROR: missing theme" ; \
+	  echo ; \
+	  echo "It looks as though you are missing the themes directory."; \
+	  echo "You need to add the scientific-python-hugo-theme as a submodule."; \
+	  echo ; \
+	  echo "Please see https://theme.scientific-python.org/getstarted/"; \
+	  echo ; \
+	  exit 1; \
 	fi
 
 content/shortcodes.md:
@@ -22,8 +27,8 @@ html: themes content/shortcodes.md
 	yes | npx pagefind --site public
 
 serve: ## Serve site, typically on http://localhost:1313
-serve: themes content/shortcodes.md
-	@hugo --printI18nWarnings server
+serve: html
+	@hugo --printI18nWarnings serve
 
 clean: ## Remove built files
 clean:
